version: "3.6"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8
    cap_add:
      - SYS_NICE
    volumes:
      - db_data:/var/lib/mysql
      - db_log:/var/log/mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
      MYSQL_DATABASE: ${TYPEORM_DATABASE}
      MYSQL_USER: ${TYPEORM_USERNAME}
      MYSQL_PASSWORD: ${TYPEORM_PASSWORD}
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}

volumes:
  db_data:
    driver: local
  db_log:
    driver: local